/**
 * Copyright 2013 China Mobile Research Institute. All Right Reserved
 *
 * This file is owned by China Mobile and you may not use, modify, copy,
 * redistribute this file without written permissions.
 *
 * These Terms of Use define legal use of this file, all updates, revisions,
 * substitutions for you. All rights not expressly granted to you are reserved
 * by Chinamobile.
 */
package com.cloudmaster.cmp.util.createXML;

import java.io.FileOutputStream;
import java.util.List;

import org.apache.log4j.Logger;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;

import com.cloudmaster.cmp.alarm.view.dao.AlarmViewDomain;

/**
 * CreateXML
 * @author <a href="mailto:liy_neu@neusoft.com">liyang</a>
 * @version 1.0.0 18 Mar 2012
 */
public class CreateXML {
    // log
    private static final Logger logger = Logger.getLogger(CreateXML.class);

    // 应答结果
    public String result = "success";

    // 节点
    private Element node;

    // 关系
    private Element link;

    /**
     * 生成数据
     * @param alarmDomains 数据
     * @param path 路径
     * @return
     */
    public String createData(List<AlarmViewDomain> alarmDomains, String path) {
        // 创建根节点
        Element data = new Element("data");
        // 将根节点添加到
        Document doc = new Document(data);
        // 一层子节点
        Element nodes = new Element("nodes");
        Element links = new Element("links");
        Element resources = new Element("resources");
        // 将一层子节点添加到根节点中
        data.addContent(nodes);
        data.addContent(links);
        data.addContent(resources);
        // 一层子节点nodes的子节点
        node = new Element("node");
        node.setAttribute("id", "n5k2");
        node.setAttribute("ip", "172.172.0.30");
        node.setAttribute("name", "C02-Cisco5K-2");
        node.setAttribute("image", "SW");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "n5k1");
        node.setAttribute("ip", "172.172.0.31");
        node.setAttribute("name", "C03-Cisco5K-1");
        node.setAttribute("image", "SW");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "n2k2");
        node.setAttribute("ip", "");
        node.setAttribute("name", "C02-Cisco2K-2");
        node.setAttribute("image", "SW");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "n2k1");
        node.setAttribute("ip", "");
        node.setAttribute("name", "C02-Cisco2K-1");
        node.setAttribute("image", "SW");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "s9306");
        node.setAttribute("ip", "");
        node.setAttribute("name", "C04-S9306-1");
        node.setAttribute("image", "SW");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "1");
        node.setAttribute("ip", "172.172.0.50");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "2");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "3");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "4");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "5");
        node.setAttribute("ip", "172.172.0.51");
        node.setAttribute("name", "D06-M5000");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "6");
        node.setAttribute("ip", "192.168.163.243");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "7");
        node.setAttribute("ip", "192.168.163.244");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "8");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "9");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "10");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "11");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "12");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "13");
        node.setAttribute("ip", "");
        node.setAttribute("name", "B07-P570");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "20");
        node.setAttribute("ip", "192.168.163.2");
        node.setAttribute("name", "G01-IBM X3950-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "21");
        node.setAttribute("ip", "192.168.163.3");
        node.setAttribute("name", "G01-IBM X3950-2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "22");
        node.setAttribute("ip", "192.168.163.4");
        node.setAttribute("name", "G01-IBM X3950-3");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "23");
        node.setAttribute("ip", "192.168.163.5");
        node.setAttribute("name", "G01-IBM X3950-4");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "24");
        node.setAttribute("ip", "192.168.163.6");
        node.setAttribute("name", "G01-IBM X3950-5");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "25");
        node.setAttribute("ip", "");
        node.setAttribute("name", "G03-CISCO UCS C200 M2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "26");
        node.setAttribute("ip", "172.172.0.45");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "27");
        node.setAttribute("ip", "172.172.0.46");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "28");
        node.setAttribute("ip", "172.172.0.47");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "29");
        node.setAttribute("ip", "172.172.0.48");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "30");
        node.setAttribute("ip", "172.172.0.40");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "31");
        node.setAttribute("ip", "172.172.0.41");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "32");
        node.setAttribute("ip", "172.172.0.42");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "33");
        node.setAttribute("ip", "172.172.0.43");
        node.setAttribute("name", "G04-HW E6000-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "34");
        node.setAttribute("ip", "172.172.0.62");
        node.setAttribute("name", "D03-IBM P550");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "35");
        node.setAttribute("ip", "172.172.0.61");
        node.setAttribute("name", "D04-IBM P570-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "36");
        node.setAttribute("ip", "172.172.0.60");
        node.setAttribute("name", "D04-IBM P570-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "37");
        node.setAttribute("ip", "172.172.0.59");
        node.setAttribute("name", "D04-IBM P570-2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "38");
        node.setAttribute("ip", "172.172.0.58");
        node.setAttribute("name", "D04-IBM P570-2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "39");
        node.setAttribute("ip", "172.172.0.127");
        node.setAttribute("name", "B05-HP DL580G7-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "40");
        node.setAttribute("ip", "172.172.0.66");
        node.setAttribute("name", "B05-HP DL580G7-2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "41");
        node.setAttribute("ip", "172.172.0.50");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "42");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "43");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "44");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D05-HP RX8640");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "45");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D06-M5000");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "46");
        node.setAttribute("ip", "");
        node.setAttribute("name", "D06-M5000");
        node.setAttribute("image", "MM");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "47");
        node.setAttribute("ip", "172.172.0.33");
        node.setAttribute("name", "G03-CISCO6120-1");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "48");
        node.setAttribute("ip", "172.172.0.34");
        node.setAttribute("name", "G03-CISCO6120-2");
        node.setAttribute("image", "SRV");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "49");
        node.setAttribute("ip", "172.172.0.12");
        node.setAttribute("name", "E01-IBM TS3310");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "50");
        node.setAttribute("ip", "");
        node.setAttribute("name", "E02-IBM X3550-M3");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "51");
        node.setAttribute("ip", "172.172.0.2");
        node.setAttribute("name", "E02-IBM SVC-1");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "52");
        node.setAttribute("ip", "172.172.0.3");
        node.setAttribute("name", "E02-IBM SVC-2");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "53");
        node.setAttribute("ip", "");
        node.setAttribute("name", "E02-IBM SVC-3");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "54");
        node.setAttribute("ip", "");
        node.setAttribute("name", "E02-IBM SVC-4");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        // node = new Element("node");
        // node.setAttribute("id", "55");
        // node.setAttribute("ip", "");
        // node.setAttribute("name", "B01-IBM B80-1");
        // node.setAttribute("image", "AS");
        // node.setAttribute("level", "-1");
        // nodes.addContent(node);
        // node = new Element("node");
        // node.setAttribute("id", "56");
        // node.setAttribute("ip", "");
        // node.setAttribute("name", "B02-IBM B80-2");
        // node.setAttribute("image", "AS");
        // node.setAttribute("level", "-1");
        // nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "57");
        node.setAttribute("ip", "172.172.0.7");
        node.setAttribute("name", "B05-IBM DS4700");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "58");
        node.setAttribute("ip", "172.172.0.8");
        node.setAttribute("name", "B05-IBM DS4700");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "59");
        node.setAttribute("ip", "172.172.0.9");
        node.setAttribute("name", "A01-IBM XIV");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "60");
        node.setAttribute("ip", "");
        node.setAttribute("name", "E03-HDS VSP");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        // node = new Element("node");
        // node.setAttribute("id", "61");
        // node.setAttribute("ip", "");
        // node.setAttribute("name", "E03-HDS VSP");
        // node.setAttribute("image", "AS");
        // node.setAttribute("level", "-1");
        // nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "62");
        node.setAttribute("ip", "172.172.0.39");
        node.setAttribute("name", "G04-E6000-1");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "63");
        node.setAttribute("ip", "172.172.0.38");
        node.setAttribute("name", "G04-E6000-2");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        node = new Element("node");
        node.setAttribute("id", "64");
        node.setAttribute("ip", "192.168.163.242");
        node.setAttribute("name", "B07-HMC");
        node.setAttribute("image", "AS");
        node.setAttribute("level", "-1");
        nodes.addContent(node);
        // node = new Element("node");
        // node.setAttribute("id", "65");
        // node.setAttribute("ip", "");
        // node.setAttribute("name", "B06-P570");
        // node.setAttribute("image", "AS");
        // node.setAttribute("level", "-1");
        // nodes.addContent(node);
        // node = new Element("node");
        // node.setAttribute("id", "66");
        // node.setAttribute("ip", "");
        // node.setAttribute("name", "B06-P570");
        // node.setAttribute("image", "AS");
        // node.setAttribute("level", "-1");
        // nodes.addContent(node);

        // 一层子节点links的子节点
        link = new Element("link");
        link.setAttribute("id", "link1");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "1");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link2");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "2");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link3");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "3");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link4");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "4");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link5");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "5");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link6");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "6");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link7");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "7");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link8");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "8");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link9");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "9");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link10");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "10");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link11");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "11");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link12");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "12");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link13");
        link.setAttribute("from", "n5k2");
        link.setAttribute("to", "13");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link14");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "20");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link15");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "21");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link16");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "22");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link17");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "23");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link18");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "24");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link19");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "25");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link20");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "26");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link21");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "27");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link22");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "28");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link23");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "29");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link24");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "30");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link25");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "31");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link26");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "32");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link27");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "33");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link28");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "34");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link29");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "35");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link30");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "36");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link31");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "37");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link32");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "38");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link33");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "39");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link34");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "40");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link35");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "41");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link36");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "42");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link37");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "43");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link38");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "44");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link39");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "45");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link40");
        link.setAttribute("from", "n2k2");
        link.setAttribute("to", "46");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link41");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "47");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link42");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "48");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link43");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "49");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link44");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "50");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link45");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "51");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link46");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "52");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link47");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "53");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link48");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "54");
        links.addContent(link);
        // link = new Element("link");
        // link.setAttribute("id","link49");
        // link.setAttribute("from","s9306");
        // link.setAttribute("to","55");
        // links.addContent(link);
        // link = new Element("link");
        // link.setAttribute("id","link50");
        // link.setAttribute("from","s9306");
        // link.setAttribute("to","56");
        // links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link51");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "57");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link52");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "58");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link53");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "59");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link54");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "60");
        links.addContent(link);
        // link = new Element("link");
        // link.setAttribute("id","link55");
        // link.setAttribute("from","s9306");
        // link.setAttribute("to","61");
        // links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link56");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "62");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link57");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "63");
        links.addContent(link);
        link = new Element("link");
        link.setAttribute("id", "link58");
        link.setAttribute("from", "s9306");
        link.setAttribute("to", "64");
        links.addContent(link);
        // link = new Element("link");
        // link.setAttribute("id","link59");
        // link.setAttribute("from","s9306");
        // link.setAttribute("to","65");
        // links.addContent(link);
        // link = new Element("link");
        // link.setAttribute("id","link60");
        // link.setAttribute("from","s9306");
        // link.setAttribute("to","66");
        // links.addContent(link);

        // 一层子节点resources的子节点
        Element nodeResources = new Element("nodeResources");
        resources.addContent(nodeResources);
        for (int i = 0; i < alarmDomains.size(); i++) {
            AlarmViewDomain alarm = alarmDomains.get(i);
            // 获取告警IP
            String alarmip = alarm.getAlarmIP();
            for (int j = 0; j < nodes.getContentSize(); j++) {
                Element device = (Element) nodes.getContent(j);
                String deviceip = device.getAttributeValue("ip");
                if (null != alarmip && null != deviceip) {
                    if (alarmip.equals(deviceip)) {
                        // 拼告警信息节点
                        node = new Element("nodeResource");
                        // 节点id对应xml设备id
                        node.setAttribute("nodeid", device.getAttributeValue("id"));
                        // 其它信息来自告警对象
                        node.setAttribute("alarmGrade", alarm.getAlarmGrade());
                        node.setAttribute("alarmID", alarm.getAlarmID());
                        node.setAttribute("alarmType", alarm.getAlarmType());
                        node.setAttribute("alarmTitle", alarm.getAlarmTitle());
                        node.setAttribute("alarmContent", alarm.getAlarmContent());
                        node.setAttribute("alarmTime", alarm.getAlarmTime());
                        node.setAttribute("firstAlarmTime", alarm.getFirstAlarmTime());
                        node.setAttribute("objectID", alarm.getAlarmIP());
                        node.setAttribute("count", alarm.getCount());
                        nodeResources.addContent(node);
                        // 由于有告警，将告警信息节点 的 告警级别对应到 设备 节点
                        device.setAttribute("level", alarm.getAlarmGrade());
                        break;
                    }
                }
            }
        }

        Format format = Format.getPrettyFormat();
        XMLOutputter xmlout = new XMLOutputter(format);
        try {
            xmlout.output(doc, new FileOutputStream(path + "/flex/data-nj.xml"));
        } catch (Exception e) {
            logger.error("createData error", e);
            result = "fail";
        }
        // 生成rock的XML
        return result;
    }
}
